/**
 * Script Packer - Bundles custom effect scripts for the WFRP2e system
 * 
 * Reads all .js files from ./scripts/ directory and packages them
 * into a single loader file that can be imported by the system.
 */
import fs from "fs";

const SCRIPTS_PATH = "./scripts/";
const OUTPUT_FILE = "./loadScripts.js";
const SYSTEM_NAMESPACE = "game.wfrp2e";

/**
 * Main packing function
 */
function packScripts() {
  // Check if scripts directory exists
  if (!fs.existsSync(SCRIPTS_PATH)) {
    console.log(`Scripts directory not found at ${SCRIPTS_PATH}. Skipping script packing.`);
    return;
  }

  const scripts = fs.readdirSync(SCRIPTS_PATH);
  let count = 0;
  let scriptObj = {};

  // Read all .js files
  for (let file of scripts) {
    if (!file.endsWith(".js")) continue;
    
    try {
      const script = fs.readFileSync(SCRIPTS_PATH + file, { encoding: "utf8" });
      const scriptName = file.split(".")[0];
      scriptObj[scriptName] = script;
      count++;
    } catch (error) {
      console.error(`Error reading script ${file}:`, error.message);
    }
  }

  // Generate loader file
  const scriptLoader = `/**
 * Auto-generated script loader for WFRP2e system
 * This file is generated by scriptPacker.js - do not edit manually
 */
export default function() {
    Hooks.on("init", () => {
        foundry.utils.mergeObject(${SYSTEM_NAMESPACE}.config.effectScripts, ${JSON.stringify(
    scriptObj,
    null,
    2
  )});
    });
}
`;

  try {
    fs.writeFileSync(OUTPUT_FILE, scriptLoader);
    console.log(`✓ Packed ${count} scripts to ${OUTPUT_FILE}`);
  } catch (error) {
    console.error(`Error writing output file:`, error.message);
  }
}

// Run packing
packScripts();
